---
- name: "create systemd service"
  template:
    src: "etc/systemd/system/systemd.service.j2"
    dest: "/etc/systemd/system/{{ item.key }}.service"
    mode: 0664
  with_dict: "{{ systemd_service }}"
  notify:
    - restart service
  tags:
    - systemd-service

- name: "create systemd timer"
  template:
    src: "etc/systemd/system/systemd.timer.j2"
    dest: "/etc/systemd/system/{{ item.key }}.timer"
    mode: 0664
  with_dict: "{{ systemd_timer }}"
#  notify:
#    - restart service
  tags:
    - systemd-service

- name: "enable service"
  systemd:
    name: "{{ item.key }}"
    enabled: "{{ item.value.enabled | default(False) }}"
    daemon_reload: yes
  with_dict: "{{ systemd_service }}"
  tags:
    - systemd-service

- name: "enable timer"
  systemd:
    name: "{{ item.key }}.timer"
    enabled: "{{ item.value.enabled | default(False) }}"
    state: started
    daemon_reload: yes
  with_dict: "{{ systemd_timer }}"
  when: ( item.value.enabled is defined and item.value.enabled | bool )
  tags:
    - systemd-service

- name: "restart service when needed"
  systemd:
    name: "{{ item.key }}"
    state: restarted
    daemon_reload: yes
  with_dict: "{{ systemd_service }}"
  when:
    - ( restart_systemd_service is defined and restart_systemd_service | bool )
    - ( item.value.enabled is defined and item.value.enabled | bool )
