---
- name: "restart service"
  systemd:
    name: "{{ item.key }}"
    state: restarted
    daemon_reload: yes
  with_dict: "{{ systemd_service }}"
  when: ( item.value.enabled is defined and item.value.enabled | bool )
